# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 762ad681ba6a77f37a3ff474d061a9df8721e6e0ed46764cef28a2d5acf9afe0f1ef9ae6120fde02c6bf2a7e465c81ee34b686fd420b8a58032546897b9b231c

test:
  secret_key_base: d823c6ae7d5dd59a042031b739cbb23b9649dc163895e4e49f7ab5c454d61bd6be259042a0a7d63280827d4f361f187cecc0e2c32701148f4383144915575216

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
